services:
  - type: web
    name: exam-ai-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    build:
      pythonVersion: 3.10.13
